### ISSUE TITLE
10월 7일. ToDo

### ISSUE THREAD

**Issue by ming-Jo** [ming-Jo/testRepo#1]
## To do
- [x] 오전 특강 열심히 듣기
- [ ] 점심 맛있게 먹기 -> 쌀국수
- [ ] 오후 특강 열심히 듣기
- [ ] 주말 푹 쉬기

***
## 요약
- 메인 페이지 배너 폰트 굵기 수정 필요
- 이미지 캡처하고 복붙 가능~ win + shift + S
![image](https://user-images.githubusercontent.com/112460344/194449476-5677cc7a-d9d0-4a12-acb8-54a45276c8db.png)

### TO-BE

**Comment by ming-Jo** [comment]
https://cdn.discordapp.com/emojis/1017320087679676416.webp?size=96&quality=lossless

**Comment by ming-Jo** [comment]
배고픕니당
